# Generated by Django 6.0 on 2025-12-18 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.IntegerField(choices=[(1, 'Square'), (2, 'Rectangle'), (3, 'Round')], default=1)),
                ('size', models.IntegerField(choices=[(1, '30 x 30cm'), (2, '50 x 50cm'), (3, '30 x 50cm'), (4, '45 x 60cm'), (5, '30cm'), (6, '50cm')], default=1)),
                ('tier', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('sponge', models.IntegerField(choices=[(1, 'Vanilla'), (2, 'Chocolate'), (3, 'Coffee'), (4, 'Carrot'), (5, 'Lemon')], default=1)),
                ('icing', models.IntegerField(choices=[(1, 'Buttercream'), (2, 'Ganache'), (3, 'Fondant'), (4, 'Royal Icing')], default=1)),
                ('message', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('colours', models.CharField(max_length=200)),
                ('quote', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.IntegerField(choices=[(1, 'Ordered'), (2, 'Completed'), (3, 'Cancelled')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
