# Generated by Django 6.0 on 2025-12-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakebuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('11:00', 'Slot 11'), ('13:00', 'Slot 13'), ('15:00', 'Slot 15'), ('17:00', 'Slot 17')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('delivery_date', 'time_slot')},
            },
        ),
    ]
